# Model hyperparameters
vocab_size: 10000
context_length: 128
d_model: 144
num_layers: 4
num_heads: 12
d_ff: 3072
rope_theta: 10000.0

# Benchmarking parameters
batch_size: 4
warmup_steps: 5
benchmark_steps: 100
forward_only: false
device: "cuda" 